application: testapp123555
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles
- url: /javascript
  static_dir: javascript
# 	expiration: 30d 0h
- url: /
  script: controllers/frontpage.py
- url: /query/edit/
  script: controllers/edit_query.py
- url: /query/view/
  script: controllers/query.py
